=== mompm/angular-CYDRE/backEnd/tools/Parameters/test_xml_dtd/prog_scheme_reference.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Definition of elements -->
<!ELEMENT ParametersGroup (ParametersGroup* | Parameter*)*>
<!ATTLIST ParametersGroup
	name CDATA #REQUIRED
>
<!ELEMENT Parameter (description? | type? | value? | default_value? | possible_values?)*>
<!ATTLIST Parameter
	name CDATA #REQUIRED
>
<!ELEMENT description (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT default_value (#PCDATA)>
<!ELEMENT possible_values (#PCDATA)>
<!ENTITY launcher SYSTEM "Launcher/Parameters_Reference/launcher_inputs.xml">
<!ENTITY library1 SYSTEM "Libraries/Library1/Parameters_Reference/library1_inputs.xml">
<!ENTITY library2 SYSTEM "Libraries/Library2/Parameters_Reference/library2_inputs.xml">

=== mompm/angular-CYDRE/backEnd/tools/Parameters/test_xml_dtd/Launcher/Parameters_Reference/prog_user.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="browser_view.xslt"?>
<?xmlspysps authentic_view.sps?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Jean-Raynald de Dreuzy (G&#233;osciences Rennes) -->
<!DOCTYPE ParametersGroup SYSTEM "../../prog_scheme_reference.dtd">
<?xml-stylesheet type="text/xsl" href="browser_view.xslt"?>
<?xmlspysps authentic_view.sps?>
<ParametersGroup name="inputs">
	<!-- Launcher parameters -->
	<ParametersGroup name="launcher">
		<Parameter name="type">
			<description>parameter of launcher</description>
			<possible_values/>
			<default_value>launcher parameter default</default_value>
			<value>parameter of result file</value>
			<type>string</type>
		</Parameter>
	</ParametersGroup>
	<ParametersGroup name="libraries">
		<ParametersGroup name="library2">
			<Parameter name="param2">
				<description>parameter of library 2</description>
				<type>int</type>
				<possible_values>&gt;=0</possible_values>
				<value></value>
				<default_value>2</default_value>
			</Parameter>
		</ParametersGroup>
	</ParametersGroup>
</ParametersGroup>
